spring:
  application:
    name: greeting-service
#agora vamos liberar endpoints, para testes e saber sobre os endpoints 
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
#propriedade especila para expor no endpoint
greeting-service:
  greeting: "Hola"
  default-value: "Mundo"

